# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


r:
  - bioc-release
  - bioc-devel
  
script:
  - R CMD build .
  - R CMD check *tar.gz

bioc_check: true