FROM rocker/shiny:4.3.1
RUN apt-get update && apt-get install -y  gdal-bin jags libcurl4-openssl-dev libgdal-dev libgeos-dev libgeos++-dev libglpk-dev libgmp-dev libicu-dev libproj-dev libssl-dev libudunits2-dev libxml2-dev make pandoc zlib1g-dev gdal-bin libcurl4-openssl-dev libgdal-dev libgeos-dev libgeos++-dev libglpk-dev libgmp-dev libicu-dev libproj-dev libssl-dev libudunits2-dev libxml2-dev make pandoc zlib1g-dev && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN Rscript -e 'remotes::install_version("RColorBrewer",upgrade="never", version = "1.1-3")'
RUN Rscript -e 'remotes::install_version("stringr",upgrade="never", version = "1.5.0")'
RUN Rscript -e 'remotes::install_version("ggplot2",upgrade="never", version = "3.4.4")'
RUN Rscript -e 'remotes::install_version("htmltools",upgrade="never", version = "0.5.6.1")'
RUN Rscript -e 'remotes::install_version("igraph",upgrade="never", version = "1.5.1")'
RUN Rscript -e 'remotes::install_version("ggrepel",upgrade="never", version = "0.9.3")'
RUN Rscript -e 'remotes::install_version("gridExtra",upgrade="never", version = "2.3")'
RUN Rscript -e 'remotes::install_version("rmarkdown",upgrade="never", version = "2.25")'
RUN Rscript -e 'remotes::install_version("knitr",upgrade="never", version = "1.44")'
RUN Rscript -e 'remotes::install_version("promises",upgrade="never", version = "1.2.1")'
RUN Rscript -e 'remotes::install_version("shiny",upgrade="never", version = "1.7.5.1")'
RUN Rscript -e 'remotes::install_version("randomForest",upgrade="never", version = "4.7-1.1")'
RUN Rscript -e 'remotes::install_version("foreach",upgrade="never", version = "1.5.2")'
RUN Rscript -e 'remotes::install_version("shinydashboard",upgrade="never", version = "0.7.2")'
RUN Rscript -e 'remotes::install_version("config",upgrade="never", version = "0.3.2")'

RUN R -e 'install.packages("BiocManager")'
RUN Rscript -e 'BiocManager::install("org.Ce.eg.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("org.Mm.eg.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("org.Dm.eg.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("org.Hs.eg.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("org.EcK12.eg.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("org.At.tair.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("GO.db",upgrade="never")'
RUN Rscript -e 'BiocManager::install("edgeR",upgrade="never")'
RUN Rscript -e 'BiocManager::install("limma",upgrade="never")'
RUN Rscript -e 'BiocManager::install("TCC",upgrade="never")'
RUN Rscript -e 'BiocManager::install("clusterProfiler",upgrade="never")'
RUN Rscript -e 'BiocManager::install("GENIE3",upgrade="never")'
RUN Rscript -e 'BiocManager::install("coseq",upgrade="never")'
RUN Rscript -e 'BiocManager::install("AnnotationDbi",upgrade="never")'
RUN Rscript -e 'BiocManager::install("genefilter",upgrade="never")'

RUN Rscript -e 'remotes::install_version("markdown",upgrade="never", version = "1.9")'
RUN Rscript -e 'remotes::install_version("loggit",upgrade="never", version = "2.1.1")'
RUN Rscript -e 'remotes::install_version("ggVennDiagram",upgrade="never", version = "1.2.3")'
RUN Rscript -e 'remotes::install_version("future",upgrade="never", version = "1.33.0")'
RUN Rscript -e 'remotes::install_version("tictoc",upgrade="never", version = "1.2")'
RUN Rscript -e 'remotes::install_version("rfPermute",upgrade="never", version = "2.5.2")'
RUN Rscript -e 'remotes::install_version("pkgload",upgrade="never", version = "1.3.3")'
RUN Rscript -e 'remotes::install_version("ggridges",upgrade="never", version = "0.5.4")'
RUN Rscript -e 'remotes::install_version("ggraph",upgrade="never", version = "2.1.0")'
RUN Rscript -e 'remotes::install_version("ade4",upgrade="never", version = "1.7-22")'
RUN Rscript -e 'remotes::install_version("doRNG",upgrade="never", version = "1.8.6")'
RUN Rscript -e 'remotes::install_version("doParallel",upgrade="never", version = "1.0.17")'
RUN Rscript -e 'remotes::install_version("plotly",upgrade="never", version = "4.10.2")'
RUN Rscript -e 'remotes::install_version("visNetwork",upgrade="never", version = "2.1.2")'
RUN Rscript -e 'remotes::install_version("shinyalert",upgrade="never", version = "3.0.0")'
RUN Rscript -e 'remotes::install_version("reshape2",upgrade="never", version = "1.4.4")'
RUN Rscript -e 'remotes::install_version("shinybusy",upgrade="never", version = "0.3.1")'
RUN Rscript -e 'remotes::install_version("pheatmap",upgrade="never", version = "1.0.12")'
RUN Rscript -e 'remotes::install_version("shinyWidgets",upgrade="never", version = "0.8.0")'
RUN Rscript -e 'remotes::install_version("shinydashboardPlus",upgrade="never", version = "2.0.3")'
RUN Rscript -e 'remotes::install_version("DT",upgrade="never", version = "0.30")'
RUN Rscript -e 'remotes::install_version("golem",upgrade="never", version = "0.4.1")'
RUN Rscript -e 'remotes::install_github("Alexandre-So/CorLevelPlot@6bca8ab2e8acd4788dd6a294f57f63841821206b")'
RUN Rscript -e 'remotes::install_github("nik01010/dashboardthemes@e931e9b422ccbfd2f1533402b2b5cdb5907f5169")'
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
EXPOSE 8086
COPY shiny-customized.config /etc/shiny-server/shiny-server.conf
CMD ["/usr/bin/shiny-server"]
